name: Deploy Documentação

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy no GitHub Pages
        run: mkdocs gh-deploy --force